# This is a basic workflow to help you get started with Actions

name: CI for LBAAS (initial)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pwd
    

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ------------------------------------
          echo "SHOULD BE CUSTOM SCRIPT HERE!"
          echo "LBAAS DEPLOYED" >> lbaas_deployed.log
          echo ------------------------------------         
          cat lbaas_deployed.log


      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'lbaas_deployed.log'
          destination_repo: 'netsquire/taste_actions'
          destination_folder: '.'
          user_email: 'netsquire@gmail.com'
          user_name: 'netsquire'
          commit_message: 'LBAAS to be deployed'

      - uses: actions/checkout@v1
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updates.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master          
