# Double valued workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LBAAS version to update'
        default: 'LBAAS <version>'
        required: true
      colo:
        description: Medallia Colocation Center
        default: Denver
        required: true      

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.version }} in colo ${{ github.event.inputs.colo }}"
